# -*- coding: utf-8 -*-
"""feature selection

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ndM0Axi0ZkMS_nRrMyp74MN_P8yXOZzE
"""

!pip install tensorflow

"""chat

"""

import random
import numpy as np
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from tensorflow import keras

"""chat"""

data = load_iris()
X = data.data
y = data.target

# Normalizar
scaler = StandardScaler()
X = scaler.fit_transform(X)

# dividir
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

"""## Representación del cromosoma

Cada individuo representa una arquitectura de red neuronal.  
Se define mediante:
- Número de capas ocultas
- Número de neuronas por capa
- Función de activación

El algoritmo genético genera diferentes combinaciones de estos parámetros.
"""

def crear_individuo():
    return {
        "capas": random.randint(1,3),
        "neuronas": random.randint(4,32),
        "activacion": random.choice(["relu", "tanh"])
    }

print(crear_individuo())

"""## Creación de la red neuronal

A partir de cada individuo, se construye dinámicamente una red neuronal usando Keras.  
El número de capas, neuronas y función de activación dependen del cromosoma.
"""

def crear_modelo(ind):
    model = keras.Sequential()

    for _ in range(ind["capas"]):
        model.add(keras.layers.Dense(ind["neuronas"], activation=ind["activacion"]))

    model.add(keras.layers.Dense(3, activation='softmax'))

    model.compile(
        optimizer='adam',
        loss='sparse_categorical_crossentropy',
        metrics=['accuracy']
    )

    return model

"""## Función de fitness

La función de fitness evalúa qué tan buena es cada arquitectura.  
Para ello:
1. Se entrena la red neuronal
2. Se evalúa con datos de prueba
3. Se obtiene la precisión (accuracy)

Esta métrica guía la evolución del algoritmo genético.
"""

def fitness(ind):
    model = crear_modelo(ind)

    model.fit(X_train, y_train, epochs=10, verbose=0)

    loss, acc = model.evaluate(X_test, y_test, verbose=0)

    return acc

"""## Inicialización de la población

Se genera una población inicial de soluciones aleatorias.  
Cada individuo representa una posible arquitectura de red neuronal.
"""

def crear_poblacion(n=4):
    return [crear_individuo() for _ in range(n)]

poblacion = crear_poblacion()

"""## Selección

Se seleccionan los individuos con mejor rendimiento (mayor accuracy).  
Estos serán utilizados para generar nuevas soluciones.
"""

def seleccionar(poblacion):
    return sorted(poblacion, key=fitness, reverse=True)

"""## Cruzamiento

Se combinan dos individuos (padres) para generar un nuevo individuo (hijo).  
Esto permite mezclar características de buenas soluciones.
"""

def cruzar(p1, p2):
    return {
        "capas": random.choice([p1["capas"], p2["capas"]]),
        "neuronas": random.choice([p1["neuronas"], p2["neuronas"]]),
        "activacion": random.choice([p1["activacion"], p2["activacion"]])
    }

"""## Mutación

Se introducen cambios aleatorios en los individuos.  
Esto ayuda a explorar nuevas soluciones y evitar quedarse en óptimos locales.
"""

def mutar(ind, prob=0.2):
    if random.random() < prob:
        ind["capas"] = random.randint(1,3)
    if random.random() < prob:
        ind["neuronas"] = random.randint(4,32)
    if random.random() < prob:
        ind["activacion"] = random.choice(["relu", "tanh"])
    return ind

poblacion = crear_poblacion(4)

for gen in range(5):
    print(f"\nGeneración {gen}")

    poblacion = seleccionar(poblacion)
    nueva = poblacion[:2]

    while len(nueva) < 4:
        p1, p2 = random.sample(poblacion[:2], 2)
        hijo = cruzar(p1, p2)
        hijo = mutar(hijo)
        nueva.append(hijo)

    poblacion = nueva

    mejor = poblacion[0]
    print("Mejor:", mejor)
    print("Accuracy:", fitness(mejor))

mejor = seleccionar(poblacion)[0]
print("\nMejor arquitectura final:", mejor)
print("Accuracy final:", fitness(mejor))

hist_mejor = []
hist_promedio = []

poblacion = crear_poblacion(4)

for gen in range(5):
    poblacion = seleccionar(poblacion)

    # evaluar toda la población
    fitness_vals = [fitness(ind) for ind in poblacion]

    mejor = max(fitness_vals)
    promedio = sum(fitness_vals) / len(fitness_vals)

    hist_mejor.append(mejor)
    hist_promedio.append(promedio)

    nueva = poblacion[:2]

    while len(nueva) < 4:
        p1, p2 = random.sample(poblacion[:2], 2)
        hijo = mutar(cruzar(p1, p2))
        nueva.append(hijo)

    poblacion = nueva

print("Mejor:", hist_mejor)
print("Promedio:", hist_promedio)

import matplotlib.pyplot as plt

plt.plot(hist_mejor, label="Mejor")
plt.plot(hist_promedio, label="Promedio")

plt.title("Comportamiento del algoritmo genético")
plt.xlabel("Generación")
plt.ylabel("Accuracy")
plt.legend()
plt.show()